version: '3.7'

services:
  app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:.
    env_file:
      - .env
    depends_on:
      - db
#      - redis
    networks:
      - coach-net

  db:
    image: postgres:13-alpine
    container_name: english_coach_db
    ports:
    - 5432:5432
    volumes:
      - ./data/pgdata/:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - coach-net

#  redis:
#    image: redis:6-alpine
#    container_name: redis
#    ports:
#      - 6379:6379
#    networks:
#      - coach-net

networks:
  coach-net:
    driver: bridge
